- name: Add PostgreSQL APT repository
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb https://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    state: present
    filename: postgresql

- name: Import PostgreSQL GPG key
  become: yes
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Update apt cache
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install PostgreSQL packages
  become: yes
  ansible.builtin.apt:
    name:
      - "postgresql-{{ postgresql_version }}"
      - "postgresql-client-{{ postgresql_version }}"
      - "postgresql-contrib-{{ postgresql_version }}"
      - "postgresql-server-dev-{{ postgresql_version }}"
      - "python3-psycopg2"
    state: present